# users
CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  login VARCHAR(255) NOT NULL,
  pass VARCHAR(255) NOT NULL
) ENGINE = INNODB;
# albums
CREATE TABLE albums (
  id INT PRIMARY KEY AUTO_INCREMENT,
  artist VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  cover VARCHAR(255) NOT NULL
) ENGINE = INNODB;